@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

####################################################

# создание объявления 1 пользолвателем
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 53b8fc76154fbf10c386ecea48e66c74445fc224

{
  "title": "Шкаф IKEA (1 пользователь)",
  "description": "Срочно"
}

###
# создание объявления 2 пользолвателем
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 7031b40ef97eaefb991098d1052adb43ac09456a

{
  "title": "Стул (2 пользователь)",
  "description": "Срочно"
}

########################################################

# фильтрация по статусу OPEN
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###
# фильтрация по статусу CLOSED
GET {{baseUrl}}/advertisements/?status=CLOSED
Content-Type: application/json

###

# фильтрация по датам (указывается диапазон)
GET {{baseUrl}}/advertisements/?created_at_after=2026-07-11&created_at_before=2026-07-12
Content-Type: application/json

######################################################

# Попытка изменить СВОЕ объявление  
PATCH {{baseUrl}}/advertisements/34/
Content-Type: application/json
Authorization: Token 53b8fc76154fbf10c386ecea48e66c74445fc224

{
  "status": "CLOSED"
}

###

# Попытка изменить ЧУЖОЕ объявление  
PATCH {{baseUrl}}/advertisements/34/
Content-Type: application/json
Authorization: Token 8777276e807f8ac2e0593b622f2da10de7044e8c

{
  "status": "CLOSED"
}

#######################################################

# Попытка удалить СВОЕ объявление 
DELETE {{baseUrl}}/advertisements/33/
Authorization: Token 53b8fc76154fbf10c386ecea48e66c74445fc224

###

# Попытка удалить ЧУЖОЕ объявление 
DELETE {{baseUrl}}/advertisements/33/
Authorization: Token 8777276e807f8ac2e0593b622f2da10de7044e8c

###########################################################
