# Generated by Django 6.0.6 on 2026-06-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='school.teacher', verbose_name='Учителя'),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
