# Generated by Django 6.0.6 on 2026-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, verbose_name='ID датчика')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя датчика')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
