# Generated by Django 6.0.6 on 2026-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measured_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='id_sensor',
        ),
    ]
